title: 二木
description: 留下脚印的地方
head:
  - - link
    - rel: icon
      href: /favicon.ico
# 指定 vuepress build 的输出目录。
dest: .vuepress/dist
host: 127.0.0.1
port: 8080
theme: ermu
# 主题配置
themeConfig:
  logo: /favicon.ico
  sidebarDepth: 2
  # 导航栏
  nav:
    - text: Java
      link: /java/
    - text: Web
      items:
        - text: JavaScript
          link: /web/javascript/
        - text: Vue
          link: /web/vue/
        - text: React
          link: /web/react/
    - text: Spring
      items: 
        - text: Spring
          link: /spring/
        - text: Spring-boot
          link: /spring-boot/
        - text: Spring-cloud
          link: /spring-cloud/
    - text: Other
      link: /other/
    - text: Archives
      link: /archives/
#    - text: About
#      link: /git/
  # 侧边导航栏
  sidebar:
    '/java/':
      - title: 地基
        children:
          - base/2018-11-13-String常用方法和源码
          - base/2018-11-14-String StringBuilder StringBuffer
      # - title: 常用的工具类
      #   collapsable: false
      #   children:
      - title: 并发编程之美
        children:
          - thread/2019-01-15-synchronized ,volatile
          - thread/2019-01-16-AbstractQueuedSynchronizer
          - thread/2019-01-20-ReentrantLock
      # - title: 性能监控调优
      #   collapsable: false
      #   children:

    '/web/javascript/':
      - title: javascript
        children:
    '/web/vue/':
      - title: Vue
        children:
    '/web/react/':
      - title: React
        children:
    '/spring/':
      - title: Spring
        children:
          - 2019-05-05-spring相关概念
    '/spring-boot/':
      - title: Springboot
        children:
    '/spring-cloud/':
      - title: SpringCloud
        children:
          - 2019-03-15-spring-cloud-eureka
    '/docker/':
      - title: Docker
        children:
          - 2019-03-12-Docker
          - 2019-03-16-maven-docker
          - 2019-03-20-GitLib+Jenkins+Docker
    '/other/':
      - title: MarkDown
        collapsable: false
        children:
          - 2019-03-10-markdown
      - title: Jenkins
        collapsable: false
        children:
          - 2019-03-12-Jenkins
      - title: Gitlib
        collapsable: false
        children:
          - 2019-03-12-GitLib
      - title: Redis
        collapsable: true
        children:
          - redis/2019-04-01-01-Redis-install
          - redis/2019-04-01-02-Redis-String
          - redis/2019-04-01-03-Redis-Hash
          - redis/2019-04-01-04-Redis-List
          - redis/2019-04-01-05-Redis-Set
          - redis/2019-04-01-06-Redis-SortSet
          - redis/2019-04-01-07-Redis-subscribe
  lastUpdated: true
  # 页底配置
  footer:
    copyright: MIT Licensed | Copyright © 2019-present Ermu
    weibo: https://weibo.com/ermu0420
    zhihu: https://www.zhihu.com/people/ermu0420
    csdn: https://me.csdn.net/qq_22420441
    github: https://github.com/ermu0420
    filing: 蜀ICP备19008309号-1
  home:
    title: 留下梦想的脚印
    labels:
      - link: /docker/
        text: Docker

      - link: /functional/
        text: Functional

      - link: /reactive/
        text: Reactive
  # 启用Vssue
  Vssue: true
  gitalk:
    dev:
      owner: ermu0420
      repo: vue-press-blog
      clientId: 3593cbaa81b50f2472df
      clientSecret: 1647121e339f77581c7cdb698b20187efde8fba3
    prod:
      owner: ermu0420
      repo: vue-press-blog
      clientId: 529e90f9d56b271223a3
      clientSecret: 211db8af09be4e0e068e3007282114dcca906d94
  plugins:
    - '@vuepress/back-to-top'